/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  evaluation_dataset: () => import("@/views/evaluation/dataset/index.vue"),
  evaluation_model: () => import("@/views/evaluation/model/index.vue"),
  evaluation_result: () => import("@/views/evaluation/result/index.vue"),
  evaluation_task: () => import("@/views/evaluation/task/index.vue"),
  evaluation_template: () => import("@/views/evaluation/template/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
