/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'evaluation',
    path: '/evaluation',
    component: 'layout.base',
    meta: {
      title: 'evaluation',
      i18nKey: 'route.evaluation',
      icon: 'mdi:clipboard-check-outline',
      order: 2
    },
    children: [
      {
        name: 'evaluation_dataset',
        path: '/evaluation/dataset',
        component: 'view.evaluation_dataset',
        meta: {
          title: 'evaluation_dataset',
          i18nKey: 'route.evaluation_dataset'
        }
      },
      {
        name: 'evaluation_model',
        path: '/evaluation/model',
        component: 'view.evaluation_model',
        meta: {
          title: 'evaluation_model',
          i18nKey: 'route.evaluation_model'
        }
      },
      {
        name: 'evaluation_result',
        path: '/evaluation/result',
        component: 'view.evaluation_result',
        meta: {
          title: 'evaluation_result',
          i18nKey: 'route.evaluation_result'
        }
      },
      {
        name: 'evaluation_task',
        path: '/evaluation/task',
        component: 'view.evaluation_task',
        meta: {
          title: 'evaluation_task',
          i18nKey: 'route.evaluation_task'
        }
      },
      {
        name: 'evaluation_template',
        path: '/evaluation/template',
        component: 'view.evaluation_template',
        meta: {
          title: 'evaluation_template',
          i18nKey: 'route.evaluation_template'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  }
];
